### ISSUE TITLE
access denied or repository not exported

### ISSUE THREAD

**Issue by queglay** [glmark2/glmark2#104]
When trying to clone this repository, I get this error:

```
[deadlineuser@workstation git]$ git clone git://git.linaro.org/people/afrantzis/glmark2.git
Cloning into 'glmark2'...
fatal: remote error: access denied or repository not exported: /people/afrantzis/glmark2.git
```

**Comment by afrantzis** [comment]
Hi! You are trying to clone from an old (and, as it seems, removed) git repo. You should be using the github repo instead (https://github.com/glmark2/glmark2.git).
