### ISSUE TITLE
No debug information on Windows

### ISSUE THREAD

**Issue by genpfault** [glmark2/glmark2#108]
The waf tooling doesn't seem to build debug info when using the Visual Studio toolchain on Windows despite `--no-debug` not being specified, ex:

    waf configure install --with-flavors=win32-glesv2 --msvc_targets="x86"

Adding a few lines to `configure_win32()` around [here](https://github.com/glmark2/glmark2/blob/24a1139dcbfd86bd02065316eaa90559e39374e1/wscript#L139) fixed it for me (read: wrote out a usable `glmark2-es2.pdb` alongside `glmark2-es2.exe` at the install location):

```
if ctx.options.debug:
    ctx.env.prepend_value('CXXFLAGS', '/Z7')
    ctx.env.prepend_value('LINKFLAGS', '/DEBUG')
```

**Comment by Joe23232** [comment]
Hi, where do you even get this for Windows?

**Comment by genpfault** [comment]
Today's Meson tooling generates a usable PDB out-of-the-box:

Building like so:

```none
> meson setup build -Dflavors=win32-gl
> ninja -C build
```

Will emit a PDB here:

```none
build\src\glmark2-win32.pdb
```
