### ISSUE TITLE
© aka A9 char is not valid UTF-8 in d.cc

### ISSUE THREAD

**Issue by ghost** [glmark2/glmark2#109]
This file/line
https://github.com/glmark2/glmark2/blob/24a1139dcbfd86bd02065316eaa90559e39374e1/src/scene-ideas/d.cc#L5
has an A9 character (the `©` one aka `(c)` / copyright) which is not valid UTF-8, according to [parsing the file with Rust](https://github.com/HarmedChronogram/Index/blob/b567d70a857d76055dbd2445ffddafd529e82c8b/src/main.rs#L28), and also according to [this](https://www.phpclasses.org/package/11059-PHP-Validate-and-repair-strings-in-UTF-8-encoding.html):
> UTF-8 characters may "collide" with extended-ASCII (also called ANSI) because
the extended-ASCII uses one-byte characters above code point 7F.  The high
order bit of a byte is of significance in the UTF-8 encoding scheme.  UTF-8,
therefore, has different (multi-byte) encoding for the ANSI characters in the
range from 80 to FF (128 to 255).  For example, the copyright symbol, a little
letter "c" in a circle, is produced at ANSI code point hexadecimal A9 (169).  
This same symbol is represented by a two-byte encoding in UTF8: C2A9.

I'm not sure if it should be changed or what, just reporting it :)
<s>Maybe</s> There are other occurrences, but I haven't tried to go past this first one while concat-ing all `.cc` files in chromium source code tree...

**Comment by howaboutsynergy** [comment]
[here](https://github.com/harfbuzz/harfbuzz/blob/670fec231d31bf7417de590efd3485f337a7330f/src/dump-khmer-data.cc#L2)'s an example of others using the (c) character correctly aka UTF-8:
$ hexdump /home/user/build/1packages/4used/chro3/ungoogled-chromium-archlinux/fetch_gclient_base/checkout_root/src/third_party/harfbuzz-ng/src/src/dump-khmer-data.cc|grep a9
0000010 a9c2 3220 3130 2038 4720 6f6f 6c67 2c65
