### ISSUE TITLE
Runtime warning: libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by malcolmlewis** [glmark2/glmark2#11]
Hi
It would appear with libpng16 the effect-2d.png in ./data/textures needs to be stripped.

If possible can the following be run and the image re-added to clean up the warning?
convert effect-2d.png -strip effect-2d.png

Cheers Malcolm

**Comment by afrantzis** [comment]
Fixed (at last), thanks for the report.
