### ISSUE TITLE
Fdroid release

### ISSUE THREAD

**Issue by paolo-caroni** [glmark2/glmark2#116]
Would be beautiful release on f-droid, so glmark2 android version can be download directly in an apk package.
For make this possible f-droid community whant the permission of the author, a fastline file structure (https://gitlab.com/snippets/1895688) and a clear tag of the release (https://github.com/glmark2/glmark2/releases).
Would you be interested?
Cheers,
Paolo

**Comment by afrantzis** [comment]
Hi Paolo! If someone is willing to put in the effort to implement what's required for f-droid integration and test things (I am currently not set up to develop/test the android build at all), then I would be happy to review and merge required metadata (e.g. fastlane) info, tag a release etc.

**Comment by paolo-caroni** [comment]
Hi!
I'm not very good in programming, but I think I can do it.
I've started to develop the required things.
I have a question, should I feel free to create a icon/logo for your project? I don't found any icon/logo in your repo.
Cheers

**Comment by paolo-caroni** [comment]
glmark2 is now on f-droid.
https://f-droid.org/en/packages/org.linaro.glmark2/

Cheers

**Comment by afrantzis** [comment]
@paolo-caroni Awesome, thanks!
