### ISSUE TITLE
--validate mostly fails without --off-screen or --frame-end=finish

### ISSUE THREAD

**Issue by cdotstout** [glmark2/glmark2#140]
Unless I also specify --off-screen or --frame-end=finish.  I think this is because the read pixels happens after the swap on frame end.

Repro'd on ubuntu 20.10:

cstout@cstout-Switch-SA5-271:~/projects/glmark2/build/out$ ./bin/glmark2-es2 --validate
=======================================================
    glmark2 2020.04
=======================================================
    OpenGL Information
    GL_VENDOR:     Intel
    GL_RENDERER:   Mesa Intel(R) HD Graphics 520 (SKL GT2)
    GL_VERSION:    OpenGL ES 3.2 Mesa 20.2.1
=======================================================
[build] use-vbo=false: Validation: Failure
[build] use-vbo=true: Validation: Success
[texture] texture-filter=nearest: Validation: Failure
[texture] texture-filter=linear: Validation: Success
[texture] texture-filter=mipmap: Validation: Failure
[shading] shading=gouraud: Validation: Failure
[shading] shading=blinn-phong-inf: Validation: Failure
[shading] shading=phong: Validation: Failure
[shading] shading=cel: Validation: Unknown
[bump] bump-render=high-poly: Validation: Failure
[bump] bump-render=normals: Validation: Failure
[bump] bump-render=height: Validation: Failure
[effect2d] kernel=0,1,0;1,-4,1;0,1,0;: Validation: Failure
[effect2d] kernel=1,1,1,1,1;1,1,1,1,1;1,1,1,1,1;: Validation: Failure
[pulsar] light=false:quads=5:texture=false: Validation: Failure
[desktop] blur-radius=5:effect=blur:passes=1:separable=true:windows=4: Validation: Failure
[desktop] effect=shadow:windows=4: Validation: Failure
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=map: Validation: Failure
[buffer] columns=200:interleave=false:update-dispersion=0.9:update-fraction=0.5:update-method=subdata: Validation: Success
[buffer] columns=200:interleave=true:update-dispersion=0.9:update-fraction=0.5:update-method=map: Validation: Success
[ideas] speed=duration: Validation: Unknown
[jellyfish] <default>: Validation: Unknown
[terrain] <default>: Validation: Unknown
[shadow] <default>: Validation: Unknown
[refract] <default>: Validation: Unknown
[conditionals] fragment-steps=0:vertex-steps=0: Validation: Failure
[conditionals] fragment-steps=5:vertex-steps=0: Validation: Failure
[conditionals] fragment-steps=0:vertex-steps=5: Validation: Failure
[function] fragment-complexity=low:fragment-steps=5: Validation: Failure
[function] fragment-complexity=medium:fragment-steps=5: Validation: Success
[loop] fragment-loop=false:fragment-steps=5:vertex-steps=5: Validation: Success
[loop] fragment-steps=5:fragment-uniform=false:vertex-steps=5: Validation: Success
[loop] fragment-steps=5:fragment-uniform=true:vertex-steps=5: Validation: Success

**Comment by afrantzis** [comment]
Thanks! In the latest version --validate implies --frame-end=finish by default.
