### ISSUE TITLE
scene-terrain targets incorrect framebuffer with --off-screen

### ISSUE THREAD

**Issue by cdotstout** [glmark2/glmark2#141]
Using --off-screen sets up a global fbo in CanvasGeneric.

In the terrain scene, the final renderer targets "onscreen" which bypasses the global fbo because the local fbo_ is 0 and set here:

https://github.com/glmark2/glmark2/blob/master/src/scene-terrain/base-renderer.cpp#L60

This has performance implications on many systems (such as Intel) where display framebuffers have different formats than  offscreen framebuffers (tiling, compression, etc).

**Comment by afrantzis** [comment]
Thanks! I updated this and other scenes to ensure we use the proper, canvas FBO.
