### ISSUE TITLE
Refract may have dirty data on AMD GPU(R7 240)

### ISSUE THREAD

**Issue by weiqiuming** [glmark2/glmark2#149]
code（210 line~239 line in src/scene-refract.cpp）:
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
     glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, width_, height_, 0,GL_RGBA, GL_UNSIGNED_BYTE, 0);
     glGenerateMipmap(GL_TEXTURE_2D);
     glBindTexture(GL_TEXTURE_2D, 0);
     glGenFramebuffers(1, &fbo_);
     glBindFramebuffer(GL_FRAMEBUFFER, fbo_);
     glFramebufferTexture2D(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_TEXTURE_2D,tex_[DEPTH], 0);
     glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D,tex_[COLOR], 0);

In this code,a normal texture is alloced  by glTexImage2D.Then mipmap is generated by glGenerateMipmap.
BUT!!!
in case of  the driver does not clear the texture:  We don't upload data here，the data of texure is dirty!If mipmap is generated at this time, the data of all level will be dirty.

The right way to do this is to draw pixels into the normal texture and then generate mipmap.

**Comment by afrantzis** [comment]
Thanks!
