### ISSUE TITLE
Broken configure check for sqrt

### ISSUE THREAD

**Issue by jwakely** [glmark2/glmark2#15]
The configure check for sqrt does:

        p=(void*)(sqrt);

This is not valid because `sqrt` is an overloaded function. A conforming C++ standard library (such as libstdc++ in GCC 6) provides multiple overloads of `sqrt` and the code above fails to compile.

**Comment by jwakely** [comment]
Is it even necessary to test for sqrt? It's 2016, it's been in the C++ standard for 18 years.

**Comment by graysky2** [comment]
I am unable to build due to this failure:
```
Checking for function sqrt               : not found
```

Related to this issue?  Can I easily circumvent?

**Comment by mis2** [comment]
See https://github.com/glmark2/glmark2/pull/19 for a fix to remove the sqrt test.

**Comment by graysky2** [comment]
@mis2 - Yes, I should have updated this referencing your patch which I put into the PR #19

**Comment by Gnurou** [comment]
This is also fixed (IMHO in a more appropriate way) by https://github.com/glmark2/glmark2/pull/24

**Comment by afrantzis** [comment]
Fixed by applying Gnurou's fix.
