### ISSUE TITLE
compilation fails with lld

### ISSUE THREAD

**Issue by RiedleroD** [glmark2/glmark2#157]
Compilation fails on arch linux; relevant configuration in `/etc/makepkg.conf` is:

```
CPPFLAGS="-D_FORTIFY_SOURCE=2 -march=native -O2 -pipe -fno-plt -fuse-ld=lld"
CFLAGS="-march=native -O2 -pipe -fno-plt -fuse-ld=lld"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
```

Tested with glmark2-2021.02-1, gcc-11.1.0-1 and lld-12.0.0-1. I can provide more information if needed.

**Comment by RiedleroD** [comment]
I suppose it is, but I can't tell because the compilation actually terminates even sooner now. It's about the same error, but with `glmark2-drm` instead of `glmark2-wayland` now.

glmark2-2021.02-1, gcc-11.1.0-1, lld-12.0.1-1

**Comment by afrantzis** [comment]
I am not able to reproduce this error with gcc-11.2.0, lld-13.0.1 with the specified flags (tried on Debian testing, though, not Arch). Is this still an issue on Arch?

**Comment by RiedleroD** [comment]
yes. tested with glmark2-2021.12-1, lld-13.0.1-1, gcc-11.2.0-4.

The log looks very similar, but a bit shorter: [log.txt](https://github.com/glmark2/glmark2/files/8497011/log.txt)

**Comment by afrantzis** [comment]
Thanks for the log. By enabling LTO in my build I was able to reproduce the issue you are describing. This seems to be an issue with lld being incompatible with gcc for LTO, see https://bugs.llvm.org/show_bug.cgi?id=42446.

For the same issue affecting another package on arch, and some more details, see https://github.com/systemd/systemd/issues/15428 .

**Comment by RiedleroD** [comment]
ah, thanks for the info! Hopefully other people with the same issue will stumble over this thread in the future.
