### ISSUE TITLE
Segfaults when EGL_VERSION string advertises less than EGL 1.4

### ISSUE THREAD

**Issue by ydirson** [glmark2/glmark2#160]
glmark2 makes use of `eglBindAPI` from EGL 1.2 and `eglGetCurrentContext` from EGL 1.4.  When `eglQueryString(EGL_VERSION)` returns an older version, those function pointers are set to NULL, even when libEGL.so exports the symbol.  The code does not check for this, and segfaults.

This is a bit annoying when working on an [EGL implementation](https://github.com/ydirson/gl-streaming/), it forces to advertise for EGL 1.4 even before 1.0 is complete.

**Comment by afrantzis** [comment]
I have made some changes in https://github.com/glmark2/glmark2/commit/06e78b67702b5413335ecdf1ae816da9c20f6ed9 that should allow running with EGL < 1.4, by gracefully skipping unavailable EGL functions. Let me know how this works for you.

**Comment by ydirson** [comment]
That works like a charm, no crash for any advertised version in the 1.0-1.4 range.
thx!
