### ISSUE TITLE
How to compile glmark2 to directly run on Framebuffer Device?

### ISSUE THREAD

**Issue by princesidhu62** [glmark2/glmark2#17]

**Comment by jessebarker** [comment]
There's no fbdev support, if that's what you are asking.  However, you can configure the build so that glmark2 will run directly on a DRM device (see INSTALL, but the flavors are 'drm-gl' and 'drm-glesv2').

**Comment by princesidhu62** [comment]
what changes are required if i want to port it to fbdev ?

**Comment by jessebarker** [comment]
See src/native-state.h for the required interfaces.  I'm not really any help on fbdev specifically.

**Comment by princesidhu62** [comment]
After replacing some X11 functions with fbdev functions in native-state-x11.c , was able to run glmark2 on fbdev.
