### ISSUE TITLE
`glmark2` + `cyclictest` hangs on some machines

### ISSUE THREAD

**Issue by zultron** [glmark2/glmark2#173]
Running `glmark2` and `cyclictest` at the same time can cause some machines to completely freeze.

Machines tested:
- ADLINK MXE-211:
  - CPU:  E3950
  - GPU:  Intel(R) HD Graphics 505 (APL 3) (0x5a84)
  - OS: Debian Bullseye
  - Kernel:  5.10.11 PREEMPT_RT (Debian package)
- ADLINK MXE-1501:
  - CPU:  N3160
  - GPU: Intel (need to go back and look)
  - OS:  Debian Bullseye
  - Kernel:  5.10.11 PREEMPT_RT (Debian package)
- Yanling/Iwill N15 YL-KBRL2:
  - CPU: i5-8250U
  - GPU:  Intel(R) UHD Graphics 620 (KBL GT2) (0x5917)
  - OS:  Mint 20.1
  - Kernel:  5.10.41 PREEMPT_RT (built from source)
- Asus PRIME H310M-A R2.0:  **NO HANG**
  - CPU:  i5-9400
  - GPU:  Intel(R) HD Graphics (Coffeelake 3x8 GT2)  (0x3e98)
  - OS:  Debian Buster
  - Kernel:  4.19.14 PREEMPT_RT (Debian package)

All machines ran both utilities built from recent git sources:
- `rt-tests`:  rev. 2af2bc2b
- `glmark2`:  rev. af498f4c

I haven't narrowed down which differences in CPU/GPU/OS/kernel correspond with hang/no hang.

I can test a 5.10 kernel on the Asus to see if it results in a hang (and if it does, I'd best take this issue elsewhere!).

I'd appreciate any feedback on whether this has been seen before (I didn't find anything in the issue trackers), on most promising place to look next, and if there's anything glaringly obvious I've missed.  I will try to provide any additional information that could help, and I can certainly take the issue elsewhere if this is the wrong forum.

-----
Why the PREEMPT_RT kernels:  I'm assembling [some crude scripts][1] meant to help determine a machine's suitability as a motion controller, where as low latency jitter as possible in e.g. 1kHz update thread is critical.  Intel GPUs (in most embedded form factor PCs) are latency killers, raising jitter from <30µs to well over 100µs during high GPU 3D load, so initially I've focused heavily on this issue.

[1]:  https://github.com/zultron/rt_bench

**Comment by zultron** [comment]
Update:  Booting the Buster 4.19.14 PREEMPT_RT (Debian package) kernel on the ADLINK MXE-211 didn't fix the problem, nor did copying the contents of `/lib/firmware/i915`.

**Comment by mv0** [comment]
Seems the common denominator here is i915 and rt kernels, or the combination of the two. Speculate that cyclictest probably exercices some code paths in the i915 driver, that aren't really supposed to be working on rt kernel? I'd probably redirect this at the kernel folks.

**Comment by zultron** [comment]
Thanks, @mv0, I'll do that.  There are relevant-looking "Intel-gfx" etc. lists at https://lists.freedesktop.org .
