### ISSUE TITLE
Strange scores on Raspberry Pi

### ISSUE THREAD

**Issue by solskogen** [glmark2/glmark2#186]
I did a couple of glmark tests on the Pi using Arch Linux ARM, and the score I get somewhat confuses me. 

glmark drm: 56
glmark-es2-drm: 56

glmark-wayland: 228
glmark-es2-wayland: 228

glmark xorg: 146
glmark-e2 xorg: 290

the drm is done in KMSDRM using the kms driver which is the default on the Pi now. 56 seems like quite a low number. For the untrained eye the performance test doesn't look any different on drm than on wayland or xorg.

**Comment by solskogen** [comment]
The one from git/master was giving some better results:

glmark-drm: 291
glmark-es2-drm: 291

glmark-wayland: 228
glmark-es2-wayland: 228

glmark xorg: 146
glmark-es2 xorg: 290

**Comment by afrantzis** [comment]
Hi! In older glmark2-drm versions, the FPS value was capped by the monitor refresh rate (i.e., vsync). This restriction was lifted in 4f8a2069a8ceb9d36abb4247fd180da75f233a72, hence the improved scores you are seeing with glmark2-drm in master. HTH.
