### ISSUE TITLE
GLMark2 GBM Vivante GPU Driver

### ISSUE THREAD

**Issue by titolini72** [glmark2/glmark2#192]
Hello,
Trying GLMark2 GBM Backend against Vivante GPU stack, it doesn't work. With Etnaviv driver it works though.

Diving into the source I notice some things btw. Any backend I used (DRM or Wayland) end up here CanvasGeneric::update().
When a swap is requested a GL swap and flip is called. In either DRM and Wayland, this flip releases buffers, whereas does nothing in GBM (see native-state-gbm.cpp). In our side this has a genuine impact as buffer are never released.

Can you please have a look on a patch I did ? to make it works ?

Thanks in advance
[0002-Solve-Swap-Flip-sequence.txt](https://github.com/glmark2/glmark2/files/10267437/0002-Solve-Swap-Flip-sequence.txt)

**Comment by chealy** [comment]
Out of curiosity, have you thought about just using etnaviv instead of the Vivante blob driver?  I've had better experiences with etnaviv for both platform integration and performance with etnaviv across multiple different platforms.

**Comment by titolini72** [comment]
Hi Chealy,
As working with VeriSilicon, there is no room for using other than them ;)

**Comment by afrantzis** [comment]
Thanks! I have merged (a small variation of) the patch. Normally, GBM/EGL shouldn't need this flip sequence (i.e., it should be able to render to the same buffer), but this is the more expected way to use the API.
