### ISSUE TITLE
Unable to compile as C++11 or C++14

### ISSUE THREAD

**Issue by jwakely** [glmark2/glmark2#20]
Your `wscript` file uses `-Werror`

That means glmark2 cannot be compiled with C++11 or later, because you use `std::auto_ptr` which produces warnings about deprecation since C++11.

You should either stop using `-Werror` by default (because you have no idea what warnings new compilers will find in your code, preventing users from building it just because they don't use the same compiler version as you) or add something like `-Wno-deprecated-declarations` to CXXFLAGS.

**Comment by jwakely** [comment]
I see that fa71af2dfab711fac87b9504b6fc9862f44bf72a added a `--no-werror` option, I would still advise adding `-Wno-deprecated-declrations` to the default flags.

**Comment by afrantzis** [comment]
Fixed by applying Gnurou's fix (move to c++14 and unique_ptr). I also removed -Werror by default (can be enabled if needed by setting CXXFLAGS when configuring). Thanks!
