### ISSUE TITLE
glmark2 starts but then immediately closes

### ISSUE THREAD

**Issue by Jacobw1oo** [glmark2/glmark2#207]
On arch aarch64 pinephone pro and inside a chroot debian aarch64.
glmark starts but then immediately closes
on both os's
glmark -d 
loads the 3ds horse model but then
[build] use-vbo=false: FPS: 0 FrameTime: inf ms
and then it closes

Note: this issue affects other applications at random. 
Full Log: 
=======================================================
glmark2 2023.01
=======================================================
OpenGL Information
GL_VENDOR: Panfrost
GL_RENDERER: Mali-T860 (Panfrost)
GL_VERSION: 3.1 Mesa 23.0.0-devel (git-120202c675)
Surface Config: buf=32 r=8 g=8 b=8 a=8 depth=24 stencil=0 samples=0
Surface Size: 800x600 windowed
=======================================================
[build] use-vbo=false: FPS: 0 FrameTime: inf ms
=======================================================
glmark2 Score: 0
=======================================================

**Comment by kode54** [comment]
I have the same problem on a Radeon RX 6700 XT, using Mesa 24.0.3 on Arch x86_64.

**Comment by Jacobw1oo** [comment]
Thank you for that amazing answer, i have moved to new to a new phone, GPU, Android 13, Termux Linux, Newest Mesa. Sorry i had left this open. Hope you have a great week.

**Comment by kode54** [comment]
The PR is not merged yet though, so the issue still stands with some compositors. Glad I was able to help diagnose the issue, though.
