### ISSUE TITLE
I'd like to get the .3ds loading functions.

### ISSUE THREAD

**Issue by AyoubCoding21** [glmark2/glmark2#223]
Hello, I am building a benchmark (early versions available on my github) and now im using some .3ds models (inspired from your models) and id like to put a function that loads the .3ds files' vertices and indices to draw them on the screen so can you send me the code that you used for this benchmark ? Thank you .

**Comment by afrantzis** [comment]
Hello, the code for the .3ds model loading can be found in https://github.com/glmark2/glmark2/blob/master/src/model.cpp . You are free to use the code as long as you respect the terms of the license (GPLv3+). If the license is not a good match for your needs or incompatible with your code, I am sure you will be able to find other online resources for .3ds loading. Perhaps using an external library like https://www.assimp.org/  would be even better.
