### ISSUE TITLE
Windows build exe contains hardcoded path to shaders files - option to make it relative?

### ISSUE THREAD

**Issue by LowLevelMahn** [glmark2/glmark2#238]
1. open VS2022 x64 console
2. cd c:\temp
3. git clone https://github.com/glmark2/glmark2.git
4. cd glmark2
5. meson setup build -Dflavors=win32-gl
6. ninja -C build
7. .\build\src\glmark2-win32.exe

> ←[1;31mError←[0m: Failed to open "c:/share/glmark2/shaders/desktop.vert"
←[1;31mError←[0m: Failed to open "c:/share/glmark2/shaders/desktop-blur.frag"
←[1;31mError←[0m: Failed to add vertex shader from file None:
←[1;31mError←[0m:   WARNING: 0:4: '' :  #version directive missing
←[1;31mError←[0m:
←[1;31mError←[0m:

i got no `c:/share/glmark2/shaders/` folder my folder is under `c:\temp\glmark2\data\shaders`

is there a way to setup with meson that the data folder is relative to the executable or something?

**Comment by afrantzis** [comment]
You can use:
1. the `data-path` meson option (`-Ddata-path=...`) to hardcode a different path
2. the `--data-path=...` runtime option to override the data path at runtime

**Comment by LowLevelMahn** [comment]
`.\build\src\glmark2-win32.exe --data-path=.\data`

works - thank you
