### ISSUE TITLE
Invalid glmark2 GLES shader code + segfault after shader compilation fail

### ISSUE THREAD

**Issue by eero-t** [glmark2/glmark2#25]
Ubuntu version of glmark2-es2 has invalid shader code.  With GLES, glmark2 uses different default precision for vertex and fragment shaders, but some of the glmark2 tests use common uniforms in multiple stages without explicitly specifying their precision, so they don't match.

However, any uniforms that are declared (even if they are not used) must have matching precision on all shader stages.  See "4.3.5 Uniform Variables" in:
  https://www.khronos.org/registry/gles/specs/3.1/GLSL_ES_Specification_3.10.pdf

"Uniforms in the vertex and fragment shaders share a single global name space. Hence, the types, precisions and any location specifiers of all declared uniform variables with the same name must match across shaders that are linked into a single program."

While glmark2-es2 requests GLES v2 context and v2 spec doesn't explicitly state this requirement like later spec versions do, mismatching precision is a clear bug.

This bug is with uniforms declared in shaders used in following tests:
- ideas ("modelview" uniform declared also in FS but not used)
- jellyfish ("uCurrentTime" uniform used both in VS & FS)
- terrain ("viewMatrix" uniform declared also in FS but not used)

In case of ideas & terrain, it's enough just to remove the unused uniform declaration, in jellyfish test the correct precision needs to be used/specified in both shader stages.

PS. Mesa gives GLES 3.x context when v2 is requested and Mesa git version will enforce this check, as it's required by Khronos conformance tests.
- With terrain test Glmark2 segfaults after shader compilation fails, with the other two tests it checks whether shader compilation succeeds and gracefully exits when it didn't.

More info: https://bugs.freedesktop.org/show_bug.cgi?id=97532

**Comment by afrantzis** [comment]
Thanks for reporting. I will remove the unused FS uniforms from ideas and terrain.

I am a puzzled by the error in jellyfish, though. The uCurrentTime uniform has highp precision in the FS, so it should match the precision in the VS. Here is the relevant final fragment shader code (the precision statements are this way due to automatic code generation):

#ifdef GL_ES
precision mediump float;
#endif
#ifdef GL_ES
precision highp float;
#endif
...
uniform float uCurrentTime;

**Comment by eero-t** [comment]
Thanks, I added following Mesa bug for that case:
https://bugs.freedesktop.org/show_bug.cgi?id=97804

**Comment by eero-t** [comment]
Mesa bug is now also fixed (in Mesa git), so all glmark2 tests work now also with GLES version.
