### ISSUE TITLE
main: Could not initialize canvas

### ISSUE THREAD

**Issue by Nikhill777** [glmark2/glmark2#35]
While running the binary the issue was seen
command = glmark2
output      = Error: main: Could not initialize canvas

command = glmark2-es2
output      = Error: main: Could not initialize canvas

The ubuntu version which i am using is 
$lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 16.04.2 LTS
Release: 16.04
Codename: xenial

$uname -a
Linux rgx-hood-tc2-2 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by afrantzis** [comment]
Some questions:

Are you running under X11?
Is the DISPLAY environment variable properly set?
Does running "glmark2 -d" give any more information?
What does running "glxinfo" say?

**Comment by Nikhill777** [comment]
> Are you running under X11?
Yes i am running under x11 system 

> Is the DISPLAY environment variable properly set?
Yes. I have set it to :0.0

>Does running "glmark2 -d" give any more information?
running glmark2 -d gives the same error ""Error: main: Could not initialize canvas""

>What does running "glxinfo" say?
I am not aware of that. there's no binary present named glxinfo

**Comment by afrantzis** [comment]
> I am not aware of that. there's no binary present named glxinfo

The glxinfo binary is in the mesa-utils package. Could you please install the package (sudo apt-get install mesa-utils), run the glxinfo command and paste the output here?

**Comment by Nikhill777** [comment]
running glxinfo gives the following output
glxinfo
Error: unable to open display

**Comment by Nikhill777** [comment]
running glxinfo gives the following output
$ glxinfo
Error: unable to open display

**Comment by afrantzis** [comment]
Thanks for trying glxinfo. The glxinfo failure is essentially the same as the glmark2 one and indicates that the invoked programs can't connect to the X11 server. So this seems to a problem with you setup rather than an issue with glmark2 (or glxinfo).

I don't know what the problem is, but one possibility is that your X server is not running at :0.0. What's the output of: "ps -Af | grep Xorg"?

**Comment by Nikhill777** [comment]
Sorry for replying late......Fractured my leg and arm in a bike accident....
Looks like ldd was not liking while running the test....
Now able to run the binaries......
Just one more help.....how to build GLMark2 binary for 32 bit DDK?

**Comment by Miouyouyou** [comment]
The following command should allow you to compile 32 bits binaries on 64 bits systems. When it comes to x86 systems, at least.

```bash
LDFLAGS="-m32" CXXFLAGS="-m32" CFLAGS="-m32" ./waf configure # followed by --with-flavors=...
./waf
./waf install # if needed
```

Have a nice recovery.

**Comment by Afeather2017** [comment]
Oh. It was happened to me. And after some debugging&tracing, I found that I have to set XDG_RUNTIME_DIR=/run/user/1000 rather than /run/user/0. Fine, I leave something here to help someone in the future
