### ISSUE TITLE
How to build glmark2 for framebuffer mode?

### ISSUE THREAD

**Issue by numbqq** [glmark2/glmark2#36]
I want to run glmark2-es2 on ubuntu server, but I dot't know how to build it for framebuffer mode.

**Comment by afrantzis** [comment]
glmark2 can run in a virtual terminal with DRM/KMS, but it doesn't support fbdev if that's what you mean by framebuffer.

There is already a package in Ubuntu for the DRM/KMS backend (although it's for an old version of glmark2). Install it with 'sudo apt install glmark2-es2-drm'.

To build it yourself and run it from within the build directory (no install needed), in the glmark2 directory do:

$ ./waf configure --with-flavors=drm-glesv2 --data-path=$(pwd)/data
$ ./waf

and in a VT (not running X11) run with:

$ build/src/glmark2-es2-drm

**Comment by numbqq** [comment]
But I found this https://code.launchpad.net/~spenser-gilliland/glmark2/mali-fbdev , 
From `Recent revisions`,
```
279. By Wladimir J. van der Laan on 2013-07-20
Add fbdev-glesv2 flavor

This exercises Mesa with the EGL 'fbdev' platform.
```
Dose it is removed in recently version ?

Thanks a lot.

**Comment by afrantzis** [comment]
The branch you found was never merged to trunk/master. You can try building it and running it, but it's specific to the Mali GPU, so it may or may not work for your use case (I don't know your target hardware).

**Comment by numbqq** [comment]
Yes, my target hardware is Mali GPU. And I got it running for mali fbdev mode. 

Thanks again!

**Comment by kukakong** [comment]
> Yes, my target hardware is Mali GPU. And I got it running for mali fbdev mode.
> 
> Thanks again!

The score of glmark2-es2-fbdev may be meaningless.
Doesn't it?
