### ISSUE TITLE
Clang generate autological-unsigned-zero-compare warning.

### ISSUE THREAD

**Issue by yunlia** [glmark2/glmark2#40]
TOT  clang generates warnings like
shader-source.cc:424:18: comparison of unsigned enum expression >= 0
    is always true [-Werror,-Wtautological-unsigned-zero-compare]

The patch in the attachment fixes the issue

[clang-autological-unsigned-zero-compare.txt](https://github.com/glmark2/glmark2/files/1322277/clang-autological-unsigned-zero-compare.txt)

**Comment by afrantzis** [comment]
Thanks for the report. I have fixed this in a different way in aa17339, avoiding the problematic comparisons altogether.
