### ISSUE TITLE
offline shaders compilation

### ISSUE THREAD

**Issue by eliyam32** [glmark2/glmark2#43]
Hello, 
I would like to port the shaders to an offline compiler. 
any advise is welcome, 
thanks, 
EM

**Comment by eliyam32** [comment]
@afrantzis

**Comment by afrantzis** [comment]
Hi!

Many of the shaders are created dynamically at runtime based on options passed to the scenes. If you pass the -d/--debug flag to glmark2 you will get (among other info) a print of the final shaders used by each scene for the specific options.

Do you want to be able to use the offline-compiled shaders in glmark2 again?

**Comment by eliyam32** [comment]
Hi :+1: 

> Do you want to be able to use the offline-compiled shaders in glmark2 again?
Yes, if possible

**Comment by afrantzis** [comment]
My recommendation would be to take a look at the Shader class in src/libmatrix/program.*. The Shader class currenty accepts the shader source and compiles it using glShaderSource and glCompileShader. You could change the code to send the source to an external compiler instead and load the compilation result in the shader with glShaderBinary.

**Comment by eliyam32** [comment]
makes sense, thanks!
