### ISSUE TITLE
Android studio integration

### ISSUE THREAD

**Issue by eliyam32** [glmark2/glmark2#50]
Hi, 
I would like to integrate glmark2 to Android studio, 
any pointers ?

Thanks ! 

EM

**Comment by eliyam32** [comment]
@afrantzis

**Comment by afrantzis** [comment]
Hi! Do you mean load glmark2 in Android studio as a project? I haven't used Android Studio in a while, but I have been meaning to take a look at the Android port of glmark2 again, to ensure everything builds, update libpng/jpeg etc, so perhaps I will have some info in the following weeks.

**Comment by eliyam32** [comment]
> Do you mean load glmark2 in Android studio as a project? 
Yes.
>perhaps I will have some info in the following weeks
Ok, Thanks

**Comment by eliyam32** [comment]
I have completed the integration, 
I have used this method : 
https://developer.android.com/studio/projects/gradle-external-native-builds.html
and some other tricks. works fine.
