### ISSUE TITLE
counter for number of draw calls 

### ISSUE THREAD

**Issue by eliyam32** [glmark2/glmark2#55]
Hi, 
How to retrieve number of draw  calls?

**Comment by eliyam32** [comment]
@afrantzis ?

**Comment by afrantzis** [comment]
There is no built-in way to track draw calls, but you can easily add it with a (global) counter that's incremented after each draw call in the codebase. There are not many locations at which glmark2 calls glDraw* - "git grep glDraw" should give you all the points you will need to change.

For a more general approach, you can use some kind of GL tracing tool (apitrace is one for linux) which logs (and can replay) GL calls. You can then parse the logs to get the information you want. HTH.
