### ISSUE TITLE
Call to eglGetPlatformDisplayEXT won't compile on some platforms

### ISSUE THREAD

**Issue by tweenk** [glmark2/glmark2#56]
gl-state-egl.cpp contains the following:

```
        PFNEGLGETPLATFORMDISPLAYEXTPROC get_platform_display =
            reinterpret_cast<PFNEGLGETPLATFORMDISPLAYEXTPROC>(
                eglGetProcAddress("eglGetPlatformDisplayEXT"));

        if (get_platform_display != nullptr) {
            egl_display_ = get_platform_display(
                GLMARK2_NATIVE_EGL_DISPLAY_ENUM, native_display_, NULL);
        }
```
Where native_display_ is of type EGLNativeDisplayType. This is incorrect, because EGLNativeDisplayType is not guaranteed to be convertible to void*: EGL/eglplatform.h defines it as intptr_t or int for some platforms.

**Comment by afrantzis** [comment]
Thanks for the report. I have added a reinterpret_cast<void*> which should fix compilation issues.
