### ISSUE TITLE
Building on Debian 9, does not have libjpeg8

### ISSUE THREAD

**Issue by CloudyProton** [glmark2/glmark2#59]
I cannot build glmark2 on Debian 9 as stretch does not have libjpeg8. The waf configuration errors out with `Checking for library jpeg                : not found`. Is there a workaround for getting libjpeg.so.8 library in place?

**Comment by afrantzis** [comment]
Hi! On Debian you should install the libjpeg-dev package which will bring in libjpeg62, which is the current Debian default. glmark2 doesn't need a later version.

**Comment by afrantzis** [comment]
This is strange. Can you please try doing a clean build (i.e., remove the build/ directory and configure from start), and attach the resulting build/config.log file? Also please paste the output of 
`apt list --installed 'libjpeg*'`.

**Comment by CloudyProton** [comment]
This is from a clean run today cloned from master, running "./waf configure --with-flavors=x11-gl". Debian 9 includes libjpeg62-turbo out of the box which I can maybe get playing nice via a big dirty web of symlinks but I'd really rather not.

[config.log](https://github.com/glmark2/glmark2/files/2167246/config.log)

`libjpeg62-turbo/stable,now 1:1.5.1-2 amd64 [installed,automatic]`

**Comment by afrantzis** [comment]
Assuming the output from the 'apt list...' command is complete, it seems you are missing the -dev package for libjpeg, which provides the appropriate header files and shared library links. You can install it with `apt install libjpeg-dev`.
