### ISSUE TITLE
error upon building on raspberry pi

### ISSUE THREAD

**Issue by ric96** [glmark2/glmark2#6]
pi@raspberrypi ~/glmark2 $ sudo apt-get install libwayland-egl
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package libwayland-egl
pi@raspberrypi ~/glmark2 $ sudo ./waf configure --with-flavors=drm-glesv2 --data-path=DATA_PATH --prefix=PREFIX
Setting top to                           : /home/pi/glmark2 
Setting out to                           : /home/pi/glmark2/build 
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for 'g++' (c++ compiler)        : /usr/bin/g++ 
Checking for header stdlib.h             : yes 
Checking for header string.h             : yes 
Checking for header unistd.h             : yes 
Checking for header stdint.h             : yes 
Checking for header stdio.h              : yes 
Checking for header jpeglib.h            : yes 
Checking for library m                   : yes 
Checking for library jpeg                : yes 
Checking for function memset             : yes 
Checking for function sqrt               : yes 
Checking for program pkg-config          : /usr/bin/pkg-config 
Checking for 'libpng12' >= 1.2           : yes 
Checking for 'x11'                       : yes 
Checking for 'gl'                        : not found 
Checking for 'egl'                       : yes 
Checking for 'glesv2'                    : yes 
Checking for 'libdrm'                    : yes 
Checking for 'gbm'                       : yes 
Checking for 'mirclient'                 : not found 
Checking for 'wayland-client'            : yes 
Checking for 'wayland-egl'               : not found 
Prefix                                   : /home/pi/glmark2/PREFIX 
Data path                                : DATA_PATH 
Including extras                         : No 
Building flavors                         : ['drm-glesv2'] 
'configure' finished successfully (15.539s)
pi@raspberrypi ~/glmark2 $ ./waf
Waf: Entering directory `/home/pi/glmark2/build'
Could not create the directory /home/pi/glmark2/build/doc
pi@raspberrypi ~/glmark2 $ sudo ./waf
Waf: Entering directory`/home/pi/glmark2/build'
[ 1/66] cxx: src/benchmark-collection.cpp -> build/src/benchmark-collection.cpp.1.o
[ 2/66] cxx: src/benchmark.cpp -> build/src/benchmark.cpp.1.o
[ 3/66] cxx: src/gl-headers.cpp -> build/src/gl-headers.cpp.1.o
[ 4/66] cxx: src/gl-visual-config.cpp -> build/src/gl-visual-config.cpp.1.o
[ 5/66] cxx: src/image-reader.cpp -> build/src/image-reader.cpp.1.o
[ 6/66] cxx: src/main-loop.cpp -> build/src/main-loop.cpp.1.o
[ 7/66] cxx: src/main.cpp -> build/src/main.cpp.1.o
In file included from ../src/main.cpp:40:0:
../src/native-state-drm.h:86:5: error: ‘gbm_surface’ does not name a type
../src/native-state-drm.h: In constructor ‘NativeStateDRM::NativeStateDRM()’:
../src/native-state-drm.h:46:9: error: class ‘NativeStateDRM’ does not have any field named ‘surface_’
Waf: Leaving directory `/home/pi/glmark2/build'
Build failed
 -> task in 'glmark2-es2-drm' failed (exit status 1): 
    {task 3060369680L: cxx main.cpp -> main.cpp.1.o}
['/usr/bin/g++', '-g', '-O2', '-Werror', '-Wall', '-Wextra', '-Wnon-virtual-dtor', '-I/home/pi/glmark2/build/src', '-I/home/pi/glmark2/src', '-I/home/pi/glmark2/build/src/scene-ideas', '-I/home/pi/glmark2/src/scene-ideas', '-I/home/pi/glmark2/build/src/scene-terrain', '-I/home/pi/glmark2/src/scene-terrain', '-I/home/pi/glmark2/build/src/libmatrix', '-I/home/pi/glmark2/src/libmatrix', '-I/usr/include/libpng12', '-I/usr/include/libdrm', '-DHAVE_STDLIB_H=1', '-DHAVE_STRING_H=1', '-DHAVE_UNISTD_H=1', '-DHAVE_STDINT_H=1', '-DHAVE_STDIO_H=1', '-DHAVE_JPEGLIB_H=1', '-DHAVE_MEMSET=1', '-DHAVE_SQRT=1', '-DHAVE_LIBPNG=1', '-DHAVE_X11=1', '-DHAVE_EGL=1', '-DHAVE_GLESV2=1', '-DHAVE_DRM=1', '-DHAVE_GBM=1', '-DHAVE_WAYLAND_CLIENT=1', '-DGLMARK_DATA_PATH="DATA_PATH"', '-DGLMARK_VERSION="2014.03"', '-DUSE_EXCEPTIONS', '-DGLMARK2_USE_DRM', '-DGLMARK2_USE_GLESv2', '-DGLMARK2_USE_EGL', '-D__GBM__', '../src/main.cpp', '-c', '-o', 'src/main.cpp.1.o']

**Comment by Artox** [comment]
Observed on .iMX6, debian wheezy too
