### ISSUE TITLE
Change Test Resolution

### ISSUE THREAD

**Issue by ThePreviousOne** [glmark2/glmark2#68]
I don't much care about my score.
I am more interested in how the test perform at high resolutions, say 3840x2160 or even 1920x1080.

Getting 4xxx FPS on tests at what 800x600 doesn't tell me anything.

**Comment by afrantzis** [comment]
Hi! You can use the -s/--size WxH command line option to set the output window size, e.g, `glmark2 -s 1920x1080`. You can also use the --fullscreen command line option.

**Comment by ThePreviousOne** [comment]
Thanks
