### ISSUE TITLE
clang: 2 build errors, 1 build warning

### ISSUE THREAD

**Issue by djkurtz** [glmark2/glmark2#7]
Building glmark2 with clang has 2 errors, and 1 warning

The two errors are similar:

../src/image-reader.cpp:35:1: error: 'PNGReaderPrivate' defined as a struct here but previously declared as a class [-Werror,-Wmismatched-tags]
struct PNGReaderPrivate
^
/build/falco/tmp/portage/app-benchmarks/glmark2-285-r3/work/glmark2-285/src/image-reader.h:35:1: note: did you mean struct here?
class PNGReaderPrivate;
^~~~~
struct

../src/image-reader.cpp:284:1: error: 'JPEGReaderPrivate' defined as a struct here but previously declared as a class [-Werror,-Wmismatched-tags]
struct JPEGReaderPrivate
^
/build/falco/tmp/portage/app-benchmarks/glmark2-285-r3/work/glmark2-285/src/image-reader.h:57:1: note: did you mean struct here?
class JPEGReaderPrivate;
^~~~~
struct
2 errors generated.

And a warning:
../src/scene-buffer.cpp:187:12: error: private field 'wave_fill_' is not used [-Werror,-Wunused-private-field]
    double wave_fill_;
           ^

**Comment by afrantzis** [comment]
Fixed, thanks.
