### ISSUE TITLE
Raspberry PI - Error: Couldn't create native window

### ISSUE THREAD

**Issue by oomek** [glmark2/glmark2#71]
Hi again, Thanks for solving the issue https://github.com/glmark2/glmark2/issues/70
It's building now, but when I launch glmark2-es2-dispmanx I get the following errors:

```
Error: Error: Dispmanx only supports full screen rendering.
Error: Error: Couldn't create native window!
Error: main: Could not initialize canvas
```

This is how I installed it:
``` 
./waf configure --with-flavors=dispmanx-glesv2
./waf
sudo ./waf install
```

I launch it on RPI with no X running.

**Comment by afrantzis** [comment]
Does `glmark2-es2-dispmanx --fullscreen` work better?

**Comment by oomek** [comment]
Yes, it launches with `--fullscreen` thank you.

**Comment by 5schatten** [comment]
@afrantzis 
Maybe this should be the default way to startup dispmanx builds then?
