### ISSUE TITLE
configure fails with Python 3.7

### ISSUE THREAD

**Issue by michaelolbrich** [glmark2/glmark2#82]
With Python 3.7 `python3 ./waf configure --with-flavors=wayland-gl` fails with:
```
[...]
  File "/path/to/glmark2/waflib/Node.py", line 346, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```

See https://github.com/waf-project/waf/pull/2126

I suspect that updating waf to the latest version will fix this.

**Comment by afrantzis** [comment]
Thanks for the report. I have applied the fix from waf-project/waf#2126 for now. Moving to a new version is more involved and requires some additional testing.
