### ISSUE TITLE
Is it possible to run glmark2 without xorg

### ISSUE THREAD

**Issue by r3d9u11** [glmark2/glmark2#86]
Hi. I'm trying to run glmark2 with OpenGL ES2 on my i.mx6 (and Ubuntu 18.04-armhf) without xorg but I have got exception:
```
# glmark2-es2
Error: main: Could not initialize canvas
```
What I'm doing wrong?
Any ideas?

Thanks!

**Comment by afrantzis** [comment]
Hi! To run in a VT you need the glmark2-es2-drm variant. You can install it with `sudo apt install glmark2-es2-drm`, although that will get you the older version of glmark2 that is in the ubuntu repositories. If you can, I recommend building from latest git.

**Comment by r3d9u11** [comment]
@afrantzis thanks for hint! I tried it, but I had same troubles https://github.com/glmark2/glmark2/issues/79

**Comment by r3d9u11** [comment]
think this issue should be closed
