### ISSUE TITLE
How to install glmark2 on Windows?

### ISSUE THREAD

**Issue by hickford** [glmark2/glmark2#9]
Hi. Is there a Windows build of glmark2? I'd like to compare my graphics card between Windows and Linux drivers.

**Comment by null77** [comment]
Potentially this could be done via an integration with WGL.

**Comment by null77** [comment]
@jessebarker FYI

**Comment by Joe23232** [comment]
@null77 

> Potentially this could be done via an integration with WGL.

That doesn't work mate I have tried it.
